name: Deploy Tagged Containers
on:
  push:
    tags:
      - '*'

jobs:
  tags:
    runs-on: ubuntu-latest
    name: Extract Semvar Tags
    outputs:
      major: ${{ steps.tag.outputs.major }}
      minor: ${{ steps.tag.outputs.minor }}
      patch: ${{ steps.tag.outputs.patch }}
    steps:
    - id: tag
      run: |
        MAJOR_VERSION=$(echo $GITHUB_REF | sed -rn 's#^/refs/tags/(v3)\.([0-9]+)\.([0-9]+)$#\1#p')
        echo ${MAJOR_VERSION}
        echo "::set-output name=major::${MAJOR_VERSION}"
        MINOR_VERSION=$(echo $GITHUB_REF | sed -rn 's#^/refs/tags/(v3)\.([0-9]+)\.([0-9]+)$#\1.\2#p')
        echo ${MINOR_VERSION}
        echo "::set-output name=minor::${MINOR_VERSION}"
        PATCH_VERSION=$(echo $GITHUB_REF | sed -rn 's#^/refs/tags/(v3)\.([0-9]+)\.([0-9]+)$#\1.\2.\3#p')
        echo ${PATCH_VERSION}
        echo "::set-output name=patch::${PATCH_VERSION}"
  deploy-github-containers:
    needs: tags
    name: Github Registry tag
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - php-apache
          - nginx
          - fpm
          - fpm-dev
          - admin
          - migrate-database
          - update-frontend
          - consume-messages
          - mysql
          - mysql-demo
    steps:
    - name: ${{ matrix.image }} to Github Registry
        run: |
          echo ${{needs.tags.outputs.major}}
          echo ${{needs.tags.outputs.minor}}
          echo ${{needs.tags.outputs.patch}}
